stages:
 - build
 - run
 - plot

image: rootproject/root-conda

hello world:
  script:
    - echo "Hello World"

build_skim:
  stage: build
  script:
    - pwd
    - echo ">>> Compile skimming executable ..." &&  \
    - COMPILER=$(root-config --cxx) &&  \
    - FLAGS=$(root-config --cflags --libs) &&  \
    - time $COMPILER -g -std=c++11 -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS
  artifacts:
    paths:
    - skim
    expire_in: 1 week
    
skim_higgs:
  stage: run
  dependencies: 
    - build_skim
  script:
    - pwd
    - ls
    - echo $SERVICE_PASS | kinit $CERN_USER@CERN.CH
    - xrdcp root://eosuser.cern.ch//eos/user/m/meehan/APBootCampFeb20/GluGluToHToTauTau.root GluGluToHToTauTau.root
    - ./skim GluGluToHToTauTau.root GluGluToHToTauTau_skimmed.root 19.6 11467.0 0.1
    


